### ISSUE TITLE
Cannot find file in the same directory

### ISSUE THREAD

**Issue by chenglou** [jonase/kibit#123]
`lein kibit bla.clj` in the same directory as bla.clj fails to find the file.

(I'd fix the issue, but I'm a clj newb and I don't know how to make lein use my local kibit fork with `lein kibit`. Any idea?)

**Comment by BenjaminVanRyseghem** [comment]
- Go in your fork
- Increase version number
- Run `$lein install` in your fork root directory
- Use the corresponding increased version number in the `project.clj` file of the project you want to run kibit against

It should work :smile:

**Comment by chenglou** [comment]
Humm... I bumped mine to 1.0.0 and `lein install`ed it. With `:plugins [[lein-kibit "1.0.0"]]` in a test directory. `lein kibit bla.clj` gave me:

```
Could not find artifact lein-kibit:lein-kibit:jar:1.0.0 in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
```

**Comment by danielcompton** [comment]
I'm not quite sure what's going on with your lein install sorry. There will be a new version of kibit coming out which will include all of the latest changes, so you should be able to just use that very soon.
