### ISSUE TITLE
provide alternative rules as cli arg or via project.clj

### ISSUE THREAD

**Issue by postspectacular** [jonase/kibit#128]
Most of the built in rules seem to be primarily designed for writing idiomatic code, but are sometimes not so suitable when trying to optimize for speed. Therefore it'd be great if one could specify a path to a rules file or namespace to be used **in place of the defaults** (not mixed in). This would enable a whole bunch of other use cases (restrict check to compliance for only certain structures, DSL checks etc.)

**Comment by danielcompton** [comment]
This is definitely something I'm wanting to do, it's being tracked in #66 so I'll close this one.
