### ISSUE TITLE
A webhook for kibit on GitHub

### ISSUE THREAD

**Issue by ftomassetti** [jonase/kibit#133]
First of all thank you for creating this project: it is amazing and it helped me improving the quality of a couple of projects of mine ([effectivejava](https://github.com/ftomassetti/effectivejava), [civs](https://github.com/ftomassetti/civs)).

I would like to run these checks on every pull requests: is there any webhook for running kibit? Any plan to implement it? I would be glad to help on that side!

**Comment by BenjaminVanRyseghem** [comment]
if I were you, I would use travis for this, as I did [here](https://github.com/teamwall/teamwall), more precisely in the [travis fils](https://github.com/teamwall/teamwall/blob/develop/.travis.yml#L5)

note that since the latest version, kibit now returns 1 if the executions failed, so no need of a wrapper anymore

**Comment by danielcompton** [comment]
Hi @ftomassetti, Kibit isn't running as a web service at the moment, although I have considered building a CodeClimate type thing for Clojure.

As @BenjaminVanRyseghem said, you can run this yourself in Travis CI fairly easily, although I will think about a CI code quality tool for the future. One thing to consider is that Kibit can quite easily generate invalid suggestions, so I wouldn't use it to break the build based on Kibit suggestions.

**Comment by ftomassetti** [comment]
Thank you @BenjaminVanRyseghem and @danielcompton, I see that using Travis could be a nice work around but ideally I would like to have a separate hook because as Daniel said I do not want to confuse a broken build with the results of kibit reporting possible errors. I think it would be very convenient to have it run automatically, both to not forget and to help new contributors but definitely I do not want a broken build because of it.

I think that building a webhook would be fairly easy and if someone is interested into it I would be very happy to help or be involved.
