### ISSUE TITLE
Wrong suggestion: `(fn [item] [:a item])` -> :a

### ISSUE THREAD

**Issue by andrusieczko** [jonase/kibit#146]
Hey,

There's a wrong suggestion about `(fn [item] [:keyword item])`.
It should not be confused with `(fn [item] (:keyword item))`.

Example:
```
(mapcat (fn [item] [:a item]) [1 2 3]) 
; => (:a 1 :a 2 :a 3)
```
vs
```
(mapcat :a [1 2 3]) 
; => ()
```

Thanks,
Karol

P.S. A workaround I found:
```
(fn [item] (list :keyword item))
```

**Comment by danielcompton** [comment]
Thanks for reporting this, and sorry for the trouble. It looks like it's the same issue as #49. I'll keep tracking it over there.

**Comment by andrusieczko** [comment]
Oh, I haven't noticed that, sorry! Thank you!
