### ISSUE TITLE
Log message indicating no failures were found

### ISSUE THREAD

**Issue by smartoma** [jonase/kibit#160]
Kibit exits silently when there are no issues. This can be confusing and give an impression that something went wrong in process. Giving clear indication that everything is OK would make it clear for users: "Kibit found no improvments in code base" or something like that.

**Comment by arrdem** [comment]
Kibit is a linter. There's a long *nix tradition of linters and other programs terminating silently when there's nothing more to be done with an `ok` (zero) exit status. At the absolute most, when invoked within a REPL kibit could return `:ok` or some other symbolic value indicating that there were no errors. Generating output when there were no changes would screw up users myself included who depend on this silent exit behavior for automatic linting scripts.

**Comment by danielcompton** [comment]
Inclined to agree with @arrdem on this one. It would be easy to wrap Kibit with a shell script that printed a message on 0 exit code which would do what you're asking. Thanks for the report though!

**Comment by danielcompton** [comment]
Inclined to agree with @arrdem on this one. It would be easy to wrap Kibit with a shell script that printed a message on 0 exit code which would do what you're asking. Thanks for the report though!
