### ISSUE TITLE
Support Clojure 1.9 namespaced maps

### ISSUE THREAD

**Issue by brabster** [jonase/kibit#166]
Hi there,

Clojure 1.9 is introducing [namespaced maps](http://dev.clojure.org/jira/browse/CLJ-1910) and they cause an error in kibit. I appreciate that this is an upcoming feature, just a heads-up.

When kibit encounters a namespaced maps, we get

```
Check failed -- skipping rest of file
java.lang.RuntimeException: Reader tag must be a symbol
```

**Comment by danielcompton** [comment]
Thanks for this, I'll get onto it soon.

**Comment by brabster** [comment]
@danielcompton I raised the same issue for eastwood, my project uses namespaced maps if that's useful for analysis or testing, eg. https://github.com/brabster/crucible/blob/master/test/crucible/aws/dynamodb_test.clj

**Comment by jimrthy** [comment]
+1

**Comment by skuro** [comment]
`tools.reader` 1.0.0-RC1 was just released including the support for namespaced maps

**Comment by devth** [comment]
Is this possible now?

**Comment by danielcompton** [comment]
I think 1.6.0-beta2 should work with this.

**Comment by deepakjangid123** [comment]
It is in beta, when the stable version will be out.
