### ISSUE TITLE
Wrong equivalence

### ISSUE THREAD

**Issue by AndreaCrotti** [jonase/kibit#174]
Given something as simple as
`(map (fn [v] [:div]) ["hello" world"])`

Kibit would suggest the following change:

```
At src/cljs/scrabble/views.cljs:86:
Consider using:
  :div
instead of:
  (fn [v] [:div v])
```

which however is not really the same thing.

**Comment by defndaines** [comment]
Looks to be a duplicate of #49

**Comment by danielcompton** [comment]
Yep, thanks!
