### ISSUE TITLE
file "README.md" has broken link

### ISSUE THREAD

**Issue by gitshub** [jonase/kibit#182]
Perhaps the link for "control-structures.clj", namely

	https://github.com/jonase/kibit/blob/master/src/kibit/rules/control_structures.clj
	
should be

	https://github.com/jonase/kibit/blob/master/kibit/src/kibit/rules/control_structures.clj

**Comment by AndreTheHunter** [comment]
This has been fixed in #183

**Comment by arrdem** [comment]
Closed as duplicate.
