### ISSUE TITLE
--replace argument not recognized on 0.1.3

### ISSUE THREAD

**Issue by csapp** [jonase/kibit#185]
I'm new to Clojure so I apologize if I'm doing something completely silly here, but I can't seem to get the --replace flag working on 0.1.3. I get an exception "--replace is not a valid argument" when I try to run it (-e behaves the same way). I can run kibit fine without the replace flag, and with other flags (e.g. --reporters). I inspected the contents of the jar Leiningen pulled down and they don't seem to mirror what's in this repo: no replace.clj file, no :replace logic in driver.clj. I grabbed the jar direct from https://mvnrepository.com/artifact/jonase/kibit/0.1.3 to verify that Leiningen wasn't doing any funny business and it appears to be the same - replace logic nowhere to be found. Am I doing something wrong?

Thanks!

**Comment by csapp** [comment]
Okay, so I'm probably just being dumb, as I see now that that replace.clj file was only committed last month. But I'm a bit confused because the changelog states that the replace feature is in 0.1.3, so I'm not sure if I'm supposed to be waiting for the next version for it or not.

**Comment by jmromrell** [comment]
I'm having this issue as well.

**Comment by arrdem** [comment]
`--replace` is a feature in as-yet unreleased 0.1.4. Sorry for the confusion. @danielcompton what does it take to cut a release?

**Comment by jmromrell** [comment]
The documentation is confusing because it makes it seem as though the feature already exists. If a release is not imminent, is there any way I can point to the unreleased source using leiningen? I'm guessing I can only point to released versions...

**Comment by danielcompton** [comment]
I've just released 0.1.4 and gave it a quick smoke check. Everything seemed to work ok.

**Comment by arrdem** [comment]
Great. Thanks.

**Comment by jmromrell** [comment]
Awesome. I will try it out today. Thanks for the fast turnaround!

**Comment by csapp** [comment]
Agreed, thank you!
