### ISSUE TITLE
Could not find artifact jonase:kibit:jar:0.1.4

### ISSUE THREAD

**Issue by belucid** [jonase/kibit#187]
Project works fine with kibit 0.1.3, but get the following error with 0.1.4:

`Could not find artifact jonase:kibit:jar:0.1.4`

**Comment by danielcompton** [comment]
I've just published `0.1.5-SNAPSHOT`. Can you try updating to that and let me know if it works for you? I think I've figured out what the problem was, but it'd be good to get confirmation.

**Comment by csapp** [comment]
Updating to the snapshot worked for me.

**Comment by belucid** [comment]
Thanks @danielcompton , 0.1.5-SNAPSHOT worked fine.
