### ISSUE TITLE
Nesting -> in doto confuses "unthreading" rule

### ISSUE THREAD

**Issue by seancorfield** [jonase/kibit#199]
We have some code that does something like:
```
(doto obj
      (-> (.someCall)
          (.anotherCall 42)))
```
and Kibit suggests `(.anotherCall (.someCall) 42)` for the subexpression (which would not be correct).

**Comment by devgnx** [comment]
Any progress on this?

**Comment by seancorfield** [comment]
Closing due to lack of feedback/interest.
