### ISSUE TITLE
[0.1.6-beta2] keyword function check triggered on square brackets

### ISSUE THREAD

**Issue by frerom** [jonase/kibit#204]
(fn [a]  [:k a])

Gives

    Consider using:
      :k
    instead of:
      (fn [a] [:k a])

This would be correct if there were *parentheses* inside the function `(:k a)` instead of *square brackets* `[:k a]`

**Comment by arrdem** [comment]
Hey @frerom thanks for the report. Unfortunately this is a known issue we're already tracking in #137.

Gonna close this as a duplicate.
