### ISSUE TITLE
Kibit fails check for keywords with namespace resolution

### ISSUE THREAD

**Issue by escherize** [jonase/kibit#216]
Hello! 

I'm so glad that kibit exists!

It would be even better if it could handle namespaced keyword aliases.

An example:

```{clojure}
(ns this.ns
  (:require [other.ns :as o]))

(def this-keyword-crashes-kibit ::o/apple)
```

The error:

```
Check failed -- skipping rest of file
java.lang.RuntimeException: Invalid token: ::o/apple
```

For the short term we aren't using the aliased namespaced keywords, to make kibit happy.

**Comment by danielcompton** [comment]
What version of kibit are you using? Something similar seems to work fine with 0.1.6 for me.

**Comment by escherize** [comment]
Hey @danielcompton,

Thanks for your reply!

Looks like I was using 0.1.5

Upgraded to 0.1.6 and this no longer an issue.
