### ISSUE TITLE
Runtime exception from kibit suggestion.

### ISSUE THREAD

**Issue by bago2k4** [jonase/kibit#217]
I have had this kibit suggestion:
```
Consider using:
  (update-in p1__436206# [:status] or "published")
instead of:
  (assoc p1__436206# :status (or (:status p1__436206#) "published"))
```

the problem is that if i replace that i get this error:
```
Exception in thread "main" java.lang.RuntimeException: Can't take value of a macro: #'clojure.core/or, compiling:...
```

Ping me if you need the stack trace.

Hope this helps solving a bug :)

**Comment by arrdem** [comment]
Man. This would be a bit nasty to fix, because it requires teaching Kibit that macros cannot be taken as values. This bug probably impacts several other rewrite rules.

**Comment by bago2k4** [comment]
Got it, i thought that could be the case but it was worth a try.. i wasn't hoping you could fix it for me, i wanted only to let you know.

Great work here, keep up!
